### ISSUE TITLE
Produce a "How to buy bitcoin with Euros using Bisq" video

### ISSUE THREAD

**Issue by cbeams** [bisq-network/youtube#1]
This task represents the first of the "how to" videos we'd like to produce based on the ideas in bisq-network/growth#4.

@flix1 will manage the production of this first video, in collaboration with @leomcy. Discussion is ongoing in the #youtube Slack channel now, and specific requirements and plans can be posted here to this issue as they are sorted out.

**Bounty:** 200 $BSQ

**Comment by cbeams** [comment]
In addition to this video, we'd like to write a guide that captures this same use case. The two can be used together, of course, and it would be good if those involved (@leomcy, @flix1, @francewhoa) collaborate on them, or at the very least are aware of what the others are doing. See https://github.com/bisq-network/docs/issues/21#issuecomment-353301350.

**Comment by cbeams** [comment]
@flix1 and @leomcy, please make sure to update this issue with a comment when you're looking for review. Chatting in the `#youtube` Slack channel is all good, but for "official" status updates about work (and especially for requests to review), please favor adding a comment to whatever the relevant GitHub issue is. Comments here in GitHub Issues are written through to the `#youtube` channel anyway, so you get the best of both worlds that way. Thanks!

**Comment by cbeams** [comment]
@leomcy just published this [draft of the video](https://wetransfer.com/downloads/d3b16c4c0253aa0baa2acb010571f3a520180110105008/9932f644315522893947bb0fdd5606fc20180110105008/a94ae0) (link will expire in 7 days). Here is my feedback:

1. With regard to production values, overall quality and length, I'd be happy to ship this video as-is; what follows are specific, content-related issues.
1. You mention "currencies" from other countries when demonstrating setting up a SEPA account in Bisq. There are no different "currencies" you're accepting. It's all Euros. The question is which _countries_ you are willing to accept Euro payments from.
1. When you walk people through setting up an account, you should make it very clear that this information is stored only locally on your Bisq client, and is never sent to any kind of centralized server. The only parties that will be able to see these details are those who you choose to trade with, and only after you've entered into a trade agreement with one another. The point here is to put people at ease, and to let them know that their personal information is not going to be collected in the way that centralized exchanges are forced to do.
1. When walking through the "Fund your trade" dialog, the mining fees are nearly 400% of the trade amount. Perhaps you are planning to do a larger trade for the real video, but if you stay with doing a small trade, you must explain why the mining fee is so high, otherwise people will go crazy when they see the fees are that high without any explanation. The best thing would be to do a real trade for a larger amount, so that the mining fee that they see is reasonable by comparison. The next best thing would be to explain that the reason the mining fee is so high is that your trade amount is so low for the purposes of this demo, and then to explain that most people trade for at least 0.05 BTC to make it worth their while to pay the mining fees. It sucks to have to explain this stuff at all, but we definitely can't let a 400% mining fee go un-explained in the video.
1. When you click "Transfer funds from Bisq wallet", there's too much magic going on. If this is the first video a user has ever seen, they're going to have no idea what's going on there. One way or another, we have to show / explain to the user that they must have a small amount of bitcoin—and they must have transferred that bitcoin into their Bisq wallet—before being able to make or take an offer in the first place. If this is going to be the first video in this series, then I think it's probably best to actually show funding the Bisq wallet in the first place. i.e. explain to people that they're going to need to already have some bitcoin, or to get some bitcoin from a friend or family member, and to transfer it into their Bisq wallet before taking the trade. Alternatively, we could make this a separate video, but that's probably an artificial split. Probably better if we just deal with everything in one place.
1. When you "black out" / redact certain parts of the UI (e.g. your SEPA account details), you should mention why you're doing it in the voiceover, otherwise the viewer will fixate on it and miss the point of whatever you are trying to communicate.
1. You briefly mention "going to your bank and sending the payment to the seller". Please make more of a point of this part. New Bisq users always imagine that Bisq is somehow going to integrate with their bank and make the payment for them. They need to understand very clearly that Bisq never interacts with your bank—you do, and you must do it manually, usually via your bank's online banking web interface. Just put a bit more emphasis on this fact so that people really get it.
1. The video is a bit cut off at the end. I imagine you're aware of that though.

Thanks, Leo!

**Comment by cbeams** [comment]
Note that I've uploaded the draft video to our new YouTube channel here: https://www.youtube.com/playlist?list=PLFH5SztL5cYOYcHji9pzV9p5bFbDpEs5q

This "drafts" playlist and the videos within it are all "unlisted", meaning that they're only visible to people with the links. This approach should make it as easy as possible to share and collaborate on works in progress like this one.

**Comment by cbeams** [comment]
From the Slack conversation at https://bisq.slack.com/archives/C8GR3TFH7/p1515776644000795:

![image](https://user-images.githubusercontent.com/301810/34905144-5773b89c-f853-11e7-9c51-ca7016f52bf8.png)

Thanks, @leomcy. The new draft you sent me is here: https://youtu.be/jVd6EPFqDbM

My feedback:

 - Items (2), (3), and (5) from https://github.com/bisq-network/youtube/issues/1#issuecomment-356608734 above haven't been addressed in this new draft. Can you comment as to why and/or record a (possibly final) draft that does address them?
 - I see that you've incorporated the feedback from items (4), (6) and (7) above, though, thanks.
 - When finishing the video it would be good to explain a bit more clearly that your newly bought bitcoin is now safe and sound in your Bisq wallet, where you may choose to leave it indefinitely, or you may choose to withdraw it to an external wallet, for example to a hardware wallet where you want to keep it maximally safe. This can all be done through the `Funds->Send funds` tab. You can show users that tab, click on the address that just received the bitcoin and show them the controls below for sending it to another address.

Also, @leomcy, could you accept the invitation to join our GitHub organization? You can do this at https://github.com/bisq-network, where you should see a link at the top of the page to accept my invitation to join.

**Comment by flix1** [comment]
-Item 2 is not critical. Leave as is. Better to publish today something that is less than perfect than waste more time.

-There's too much to talk about for **Item 5**, if we want to keep this tutorial under 5 minutes we should leave the explanation for another video.

-**Item 3** can be solved in 10 seconds and definitely deserves a mention.

**Comment by cbeams** [comment]
I'm fine with the above. Thanks, @flix1.

**Comment by cbeams** [comment]
@leomcy's latest draft is up at https://youtu.be/-o9CKiivyIc.

There is one unfortunate moment at around 4:20 where the "payment started" button doesn't work and Bisq asks the user to "send confirmation again". Would be good to cut that out of the video, but it's not critical.

@bisq-network/contributors, please have a look at the draft linked above, and once I've got a couple ACKs, I'll make the video public and announce it via Twitter.

Thanks, all.

**Comment by mrosseel** [comment]
+1, one note though, when creating your account you don't select the country currencies, you just select which countries you want to trade.

**Comment by flix1** [comment]
+1.

Some improvements still possible. But I would rather have a new video published every week than too much attention to detail.

I say ACK.

**Comment by cbeams** [comment]
Closing as complete. Thanks, @leomcy!

From https://twitter.com/bisq_network/status/953609146900844544:

![image](https://user-images.githubusercontent.com/301810/35043533-43c44162-fb8d-11e7-8f91-206484425da3.png)

Leo, regarding getting compensated in $BSQ, please follow the instructions at https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#submit-a-compensation-request.

**Comment by cbeams** [comment]
Thanks for the feedback, @blabno! Good feedback for future videos. /cc @flix1, @leomcy.

**Comment by Francewhoa** [comment]
About this awesome video at https://youtu.be/jVd6EPFqDbM
I love it. Very useful for newcomers. I actually learned a few things myself. Thanks :)

This is my feedback and proposals for future videos. Such as #3, #5, #6, #7.


### What I like:

1. **Unlisted video**. This is a good idea. Make it easier to collaborate. While reducing risk of publishing a video too early.

1. **High resolution 1080p60**. It's easy to read. I could easily view all details. For users with lower bandwidth they can always change their setting to stream a lower resolution. But streaming a higher resolution is not possible.

1. **Short**. Usually for newcomers short videos are more attractive. Also makes it easier to find topic of interest. I mean this video focus on one topic. Which is how to buy coins.

1. **Steps by steps**. This format is usually the most popular for newcomers. They need to know how to do x, y, z. In this case how to buy coins.

1. **Redact sensitive info**. Wise move to hide from the video the author's private account information. Otherwise there is a risk of abuse by people with immature behaviors.

1. **Congratulation**. Good idea to close the video by saying "Congratulation". It's lots of work for newcomers to go through the initial learning curve with Bisq. This Congratulation acknowledge their efforts, grow their self-confidence, and increase their change of learning more about Bisq and using it.


### Proposals for future videos:

1. **Say forward**. Say when there is a forward in time. For example at 3m11s at https://www.youtube.com/watch?v=jVd6EPFqDbM&feature=youtu.be&t=3m11s
The video was forwared roughly 30 minutes into the future. Before the forward I propose to say something like this: "I'll now forward this video roughly 30 minutes until after the 'The transaction is accepted by the blockchain' ".
For users familiar with Bisq it's obvious the the video was forward 30m. But for newcomers it's not. In other words, if they see in the video a 3 seconds delay before the transaction is accepted they will expect that. Thus the need to say both that it's 30 minutes and it's a forward.

1. **Black redact**. Instead of white. I'm referring to this section at 3m21s at https://youtu.be/jVd6EPFqDbM?t=3m21s
In this context a redaction in white is risky to create confusion for newcomers. Again for users familiar with Bisq it's obvious which section(s) were masked. But for newcomers it's not. In other words, masking using white on white or pale background is harder to understand. Also in this context white is risky to be misinterpreted as a bug. Masking in black would resolve this challenge. In addition to this, black is the most common masking color.

1. **Say "Confirmation" processing**. From 3m43s to 4m00s at https://youtu.be/jVd6EPFqDbM?t=3m43s There is a 17 seconds of silence and little or no visual action, during that silence I propose to say something like "I click on 'Yes, I have started the payment. This visual throbber at the bottom of the screen is a confirmation that the confirmation is processing. Bisq usually needs between 10 and 30 seconds to complete. For your convenience, I'll now forward the video to the next step."

1. **Remove the visual glitch**. Which is at 3m56s at https://youtu.be/jVd6EPFqDbM?t=3m56s
User familiar with Bisq know that it's not a glitch, it's masking in white. But newcomers might be confuse by this flashing white square. How about either remove the white square before the next page is display, or a black square?

1. **Introduce the "Trade process"**. This might be very useful for newcomers. I'm referring to the section at https://youtu.be/jVd6EPFqDbM?t=3m29s
On the bottom left side of the screen. How about saying "This trade progress section shows the progress so far. Your action successfully done, your present action, and your remaining action(s)."
