### ISSUE TITLE
Add channel art for YouTube channel

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/youtube#11]
To improve our YouTube presence we should think about what to put as our YouTube channel art as well. 
![YouTube channel art](https://images.zenhubusercontent.com/5a0bffe08a75884b90877eda/0e863afb-ceb6-4387-840b-0e75a8cb7a04)

**Comment by cbeams** [comment]
Agreed. I spent some time thinking about this when I set the channel up, but opted for doing nothing rather than doing something weak. Same philosophy with our empty header image at Twitter.

I've been trying to get hold of an artist I really want to work with. You just reminded me to ping him again :)

But in the meantime, suggestions welcome.

**Comment by ripcurlx** [comment]
Will give it some thoughts as well. Have to get into this YouTube thing step-by-step ;-)

**Comment by wetherweasel** [comment]
Is this still needed? Seems that there is an image now?

**Comment by m52go** [comment]
Yes, this has been taken care of. Closing.
