### ISSUE TITLE
Set custom url for channel

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/youtube#13]
To make it more easy to communicate our YouTube channel we should decide on a channel URL.

What about youtube.com/c/Bisq or shall we go for youtube.com/c/BisqNetwork?

**Comment by ripcurlx** [comment]
Welcome https://www.youtube.com/c/bisq-network!

**Comment by cbeams** [comment]
@ripcurlx, in the future, could you use the "Closing as [status]" comment convention when closing issues? In this case, "Closing as complete"? I think you've been doing these elsewhere at least some of the time. The reason is that it allows other contributors to instantly understand why this issue was closed, and what it's status is, without having to interpret or infer anything.

Also, you'll see I've updated our website YouTube links to reflect the new URL (see commit above).

Thanks!

**Comment by ripcurlx** [comment]
Will keep it in mind! 👍
